FROM jenkins:1.609.3

USER root
RUN echo "deb [arch=amd64] https://download.docker.com/linux/debian jessie release" > /etc/apt/sources.list.d/docker.list
RUN apt-key adv --recv-keys --keyserver AA8E81B4331F7F50
RUN apt-get update && apt-get install apt-transport-https ca-certificates sudo docker-engine
#echo "deb [arch=amd64] https://download.docker.com/linux/debian stretch release" \
#	    > /etc/apt/sources.list.d/docker.list \
	#&& wget https://download.docker.com/linux/debian/gpg | apt-key add - \
#	&& apt-get update \
#	&& apt-get upgrade \
#	&& apt-get install -y apt-transport-https \
#	&& apt-get install -y ca-certificates \
#	&& apt-get install -y sudo \
#	&& apt-get install -y docker-engine \
#	&& rm -rf /var/lib/apt/lists/*
RUN echo "jenkins ALL=NOPASSWD: ALL" >> /etc/sudoers
USER jenkins
